config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :posts
  devise_for :users
  #get 'home' => 'home#index', as: :home
  root to: 'blogs#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :edit, :update], param: :username do
    member { get 'avatar' }
  end
    resources :comments, only: [:create, :destroy]
  get 'admin_panel' => 'admin#index' , as: :admin
  get 'admin_panel/edit_user_role' => 'admin#edit_user_role', as: 'admin/edit_user_role'
  post 'admin_panel/edit_user_role' => 'admin#edit_user_role'

  #http://hawkins.io/2011/05/advanced_caching_in_rails/
end

app/models/blog.rb
 # encoding: utf-8
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 20 }

  def to_param
  	slug
  end 

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

  def should_generate_new_friendly_id?
  	name_changed?
	end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	skip_before_action :authenticate_user!, :only => [:index]
	load_and_authorize_resource
	require 'will_paginate/array'

	def index
		@page = params[:page]
		q = params[:user_id] ? "user_id = #{params[:user_id]}" : ''
		authenticate_user! if q != ''
		blogs = Blog.all.where(q)
		@blogs = blogs.reverse.paginate(page: @page, :per_page => 10)
	end

	def show
		@blog = Blog.find(params[:id])
		@page = params[:page]
		@posts = @blog.posts
		@posts = @posts.reverse.paginate(page: @page, :per_page => 10)
	end

	def new
		user = current_user
		@blog = user.blogs.new
	end

	def create
		user = current_user
		@blog = user.blogs.create(blog_params)
		if @blog.save
			redirect_to blog_path(@blog)
		else
			render 'new' 
		end
	end 

	def edit
		@blog = Blog.find(params[:id])
	end 

	def update
		@blog = Blog.find(params[:id])
		if @blog.update(blog_params)
			redirect_to @blog
		else
			render 'edit'
		end
	end 

	def destroy
		@blog = Blog.find(params[:id])
		@user = User.find(@blog.user_id)
		@blog.destroy
		redirect_to blogs_path(@user)
	end 

	private
	def blog_params
		params.require(:blog).permit( :name, :description)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def find_username(blog)
		user = User.find(blog.user_id)
		user.username
	end 
end

app/views/blogs/_form.html.erb
<div class = "back btn btn-default"> 
  <span class="glyphicon glyphicon-chevron-left back-arr" aria-hidden="true"></span><%= link_to 'Back', :back, class: "back-font" %>
</div>
<div class="my_field-input">
<div class="form-group">
	<%= form_for @blog do |f| %>
	<% if @blog.errors.any? %>
	<div class="alert alert-warning alert-block text-danger">
    <button type="button" class="close" data-dismiss="alert">x</button>
		<h2>
			<%= pluralize(@blog.errors.count, "error") %> prohibiten this blog from being saved:
		</h2>
		<ul>
			<% @blog.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :name, class: "attributes-f" %><br>
		<%= f.text_field :name, class: "form-control", id:"exampleInputEmail1", placeholder: "Name of the blog" %>
	</p>
	<br>
	<p>
		<%= f.label :description, class: "attributes-f" %><br>
		<%= f.text_area :description, class: "form-control", rows: "5", id: "comment", placeholder: "Share with others what your blog is about..." %>
	</p>
	<p>
		<br>
	  <div id = "button-center">
	    <div class="button-center" ><%= f.submit "Create", class: "btn btn-info btn-lg" %></div>
  </div>
	</p>
	<% end %>
	</div>
</div>

app/views/blogs/edit.html.erb
<div id="header-font"><h2 class="header-font">Edit blog</h2></div>
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="my_field">
  <% if @blogs == []%>
  <div class="panel panel-default">
    <div class="panel-body">
    <p class = "text">
    	There's no blogs yet. You can create the first one by directing this <%= link_to "link", new_blog_path, id: "link" %>.
    </p>
    </div>
  </div>
    <% else %>
    <% @blogs.each do |blog|%>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= link_to blog.name, blog_path(blog), class: "heading"%>
        </div>
        <div>
        <%= link_to blog.description, blog_path(blog), class: "list-group-item panel-footer text" %>
        </div>
        
      </div>
    <% end %>
    <%= will_paginate @blogs, class: "digg_pagination" %>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div id="header-font"><h2 class="header-font">New blog</h2></div>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="my_field">
  <div class="panel panel-primary">
    <div>
      <h2 class="header-font"><%= @blog.name %></h2>
    </div>
    <div class="panel-body">
          <div class="author attributes-f">
            Author <span class="badge attributes"><%= link_to @blog.user.username.capitalize, user_path(@blog.user), id: "link-author" %></span>
          </div>
          <div class="date attributes-f">
            <% if @blog.posts.last != nil %>
            Last update <span class="badge attributes"><%= @blog.posts.last.created_at.strftime("%d %b %Y at %H:%M ") %></span>
            <% end %>
          </div>
          <br><br>
      <% if @posts == []%>
        <p class = "text">
          Here isn't any post yet. 
        <% if @blog.user_id == current_user.id %>
          You can create the first one by directing this <%= link_to "link", new_post_path(blog_id: @blog.id), id: "link" %>.
        <% end %>
        </p>
      <% else %>
        <% if @blog.user_id == current_user.id %>
          <div class = "button-center">
          <%= link_to "Create New Post", new_post_path(blog_id: @blog.id), class: "btn btn-info" %>
          </div>
        <% end %>
        <br>
        <% @posts.each do |post| %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= link_to post.name, post_path(post), class: "heading-post" %></h3>
            </div>
            <div>
              <%= link_to post.description, post_path(post), class: "list-group-item panel-body text" %>
            </div>
          </div>
        <% end %>
    <% end %>
    <%= will_paginate @posts, class: "pager digg_pagination" %>
    <div class="button-center attributes-f">
      <%= link_to ' To all blogs of this author', blogs_path(user_id: @blog.user_id), class: "btn btn-default" %>
    </div>
    <p>
      <% if can? :update && :edit && :destroy, @blog%>
      <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-primary active" %>
      <%= link_to 'Delete', blog_path(@blog), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default active" %>
      <% end %>
    </p>
   </div>

  </div>
</div>