config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :posts
  devise_for :users
  #get 'home' => 'home#index', as: :home
  root to: 'blogs#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :edit, :update], param: :username do
    member { get 'avatar' }
  end
    resources :comments, only: [:create, :destroy]
  get 'admin_panel' => 'admin#index' , as: :admin
  get 'admin_panel/edit_user_role' => 'admin#edit_user_role', as: 'admin/edit_user_role'
  post 'admin_panel/edit_user_role' => 'admin#edit_user_role'

  #http://hawkins.io/2011/05/advanced_caching_in_rails/
end

app/views/admin/edit_user_role.html.erb
<div id="header-font"><h2 class="header-font">User list</h2></div>
<div class = "back btn btn-default"> 
  <span class="glyphicon glyphicon-chevron-left back-arr" aria-hidden="true"></span><%= link_to 'Back to Admin Panel', admin_path, class: "back-font" %>
</div>
<div class="my_field">
<br><br>
<%= form_for :page, url: admin_panel_edit_user_role_path(@page,page: @page) do |f| %>
<div class="my_table">
  <table class="table table-hover text">
    <thead>
      <tr class="color-table">
        <th>Username</th>
        <th>Email</th>
        <th>Admin Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
          <tr class="color-td"> 
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td>
            <%= hidden_field_tag('people2[]', user.id) %>
            <%= check_box_tag("people[]", user.id, user.admin?)%>
             </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <div id = "button-center">
    <div class="button-center" ><%= f.submit "Submit", class: "btn btn-info" %></div>
  </div>
  <%= will_paginate @users, class: "pager digg_pagination" %>
  <% end %>
</div>

app/views/admin/index.html.erb
<div id="header-font"><h2 class="header-font">Admin panel</h2></div>
<div class="my_field">
	<br>
	<h2 class = "heading-post" >Hello, Admin!</h2>
	<p class = "text" >Now you can start with editing the users roles.</p>
	<%= button_to 'Edit users roles', admin_edit_user_role_path, class: "btn btn-primary btn-lg"  %>
</div>