config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :posts
  devise_for :users
  #get 'home' => 'home#index', as: :home
  root to: 'blogs#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :edit, :update], param: :username do
    member { get 'avatar' }
  end
    resources :comments, only: [:create, :destroy]
  get 'admin_panel' => 'admin#index' , as: :admin
  get 'admin_panel/edit_user_role' => 'admin#edit_user_role', as: 'admin/edit_user_role'
  post 'admin_panel/edit_user_role' => 'admin#edit_user_role'

  #http://hawkins.io/2011/05/advanced_caching_in_rails/
end

app/views/shared/_navbar.erb
<div class="small-menu collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav active">
    <li><%= link_to "My Blogs", blogs_path(user_id: current_user.id), id: "menu-font"   if current_user != nil%></li>
    <li><%= link_to "My Profile", user_path(current_user), id: "menu-font"   if current_user != nil%></li>
    <li><%= link_to "Create New Blog", new_blog_path, id: "menu-font" %></li>
    <li><%= link_to "Create New Post", new_post_path, id: "menu-font" %></li>
    <% if can? :manage, :all %>
      <li><%= link_to "Admin Panel", admin_path, id: "menu-font" %></li>
    <% end %>
  </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, id: "menu-font-sign" %></li>
      <% else %> 
         <li><%= link_to "Sign In", new_user_session_path, :method => :get, id: "menu-font-sign"  %></li>
         <li><%= link_to "Sign Up", new_user_registration_path, :method => :get, id: "menu-font-sign"  %></li>
      <% end %>
    </ul>
</div>