config/routes.rb
Rails.application.routes.draw do 
  resources :blogs
  resources :posts
  devise_for :users
  #get 'home' => 'home#index', as: :home
  root to: 'blogs#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :edit, :update], param: :username do
    member { get 'avatar' }
  end
    resources :comments, only: [:create, :destroy]
  get 'admin_panel' => 'admin#index' , as: :admin
  get 'admin_panel/edit_user_role' => 'admin#edit_user_role', as: 'admin/edit_user_role'
  post 'admin_panel/edit_user_role' => 'admin#edit_user_role'

  #http://hawkins.io/2011/05/advanced_caching_in_rails/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :users, through: :views 
  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 20 }
  validates :text, presence: true, length: { minimum: 50 }

  def to_param
  	slug
  end 

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
  	name_changed? 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	@@post_name = nil

	def show
		@post = Post.find(params[:id])
		@commentable = commentable
		@comment = @commentable.comments.new
		@comments = @commentable.comments
		@route = comments_path(post_id: @post.id)
		if @post.views.where("user_id=#{current_user.id}") == []
			view = @post.views.new
			view.user_id = current_user.id
			view.save
		end
		#	Post.update_counters(@post.id, views_count: 1)
		#	#@views = @post.views.size
		#else
		#	view = nil
		#	render "show"
		#end
		#@post.views_count = @post.views.size
		#if View.where("post_id=#{@post.id} && user_id=#{current_user.id}") == []
		#	view = @post.views.new
		#	view.user_id = current_user.id
		#	view.save
		#end
		#@views = View.all.where("post_id=#{@post.id}").size
	end

	def new
		@blogs = Blog.all.where("user_id=#{current_user.id}")
		@blog = params[:blog_id] ? Blog.find(params[:blog_id]) : nil
		@blog ? @post = @blog.posts.new : @post = Post.new
		@post.blog_id = params[:blog_id] if @post == nil
	end

	def create
		@blogs = Blog.all.where("user_id=#{current_user.id}")
		blog = params[:blog_id] ? Blog.find(params[:blog_id]) : nil
		blog ? @post = blog.posts.create(post_params) : @post = Post.new(post_params)
		@post.blog_id = params[:post][:blog_id] if @post.blog_id == nil
		if @post.save
			redirect_to @post
		else
			render 'new' 
		end
	end 

	def edit
		@post = Post.find(params[:id])
	end 

	def update
		@post = Post.find(params[:id])
		#@post = Post.find_by_name(@@pidst_name) if @post == nil
		if @post.update(post_params)
			redirect_to @post
		else
			#name_of_post(params[:name])
			render 'edit' 
		end
	end 

	def destroy
		@post = Post.find(params[:id])
		@blog = Blog.find(@post.blog_id)
		@post.destroy
		redirect_to blog_path(@blog)
	end 

	private
	def post_params
		params.require(:post).permit(:name, :description, :text)
	end

	def comment_params
    	params.require(:comment).permit(:body)
  	end

  	def commentable
    if params[:user_id]
      id = params[:user_id]
      User.find(params[:id])
    else
      id = params[:post_id]
      Post.find(params[:id])
    end
    end 

    def commentable_url(commentable)
    if User === commentable
      user_path(commentable)
    else
      post_path(commentable)
    end
    end

    def name_of_post(params)
		@@post_name = params
	end 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
	<% if @post.errors.any? %>
		<div class="alert alert-warning alert-block text-danger">
	    <button type="button" class="close" data-dismiss="alert">x</button>
			<h2>
				<%= pluralize(@post.errors.count, "error") %> prohibiten this post from being saved:
			</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

app/views/posts/_form.html.erb
	<% if @post.errors.any? %>
		<div id = "error_explanation">
			<h2>
				<%= pluralize(@post.errors.count, "error") %> prohibiten this post from being saved:
			</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

app/views/posts/edit.html.erb
<div id="header-font"><h2 class="header-font">Edit post</h2></div>
	<div class = "back"> 
	  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><%= link_to 'Back', :back, class: "back-font" %>
	</div>
	<div class="my_field-input">
		<%= form_for @post, url: post_path(@post) do |f| %>
		<%= render 'errors' %>
		<p>
			<%= f.label :name, class: "attributes-f"  %><br>
			<%= f.text_field :name, class: "form-control", id:"exampleInputEmail1" %>
		</p>
		<br>
		<p>
			<%= f.label :description, class: "attributes-f"  %><br>
			<%= f.text_area :description, class: "form-control", rows: "5", id: "comment"  %>
		</p>
		<br>
		<p>
			<%= f.label :text, class: "attributes-f"  %><br>
			<%= f.text_area :text, class: "form-control", rows: "10", id: "comment"  %>
		</p>
		<p>
			<br>
		  <div id = "button-center">
		    <div class="button-center" ><%= f.submit "Create", class: "btn btn-info btn-lg" %></div>
		  </div>
		</p>
		<% end %>
</div>

app/views/posts/new.html.erb
<div id="header-font"><h2 class="header-font">New Post</h2></div>
<div class = "back btn btn-default"> 
  <span class="glyphicon glyphicon-chevron-left back-arr" aria-hidden="true"></span><%= link_to 'Back', :back, class: "back-font" %>
</div>
<div class="my_field-input">
	<% if @blog == nil && @blogs == [] %>
		<div class="panel panel-default">
		  <div class="panel-body">
				<p class = "text">
			    You don't have any blog yet. To create new post, you need to create the blog at first. You can create the your first blog by directing this <%= link_to "link", new_blog_path, id: "link" %>.
			  </p>
		  </div>
		</div>
	  <% else %>
		<%= form_for @post do |f| %>
			<%= render 'errors' %>
			<% if params[:blog_id]==nil%>
			<div class="form-group">
				<%= f.label "Select the blog", class: "attributes-f"  %>
				<%= f.collection_select(:blog_id, @blogs, :id, :name, {}, {class: "form-control"}) %>
				</div>
			<% else %>
				<%= hidden_field_tag 'blog_id', params[:blog_id] %>
			<% end %>
			<br>
			<p>
				<%= f.label :name, class: "attributes-f"  %><br>
				<%= f.text_field :name, class: "form-control", id:"exampleInputEmail1", placeholder: "Name of the post" %>
			</p>
			<br>
			<p>
				<%= f.label :description, class: "attributes-f"  %><br>
				<%= f.text_area :description, class: "form-control", rows: "5", id: "comment", placeholder: "Share with others what your post is about..."  %>
			</p>
			<br>
			<p>
				<%= f.label :text, class: "attributes-f"  %><br>
				<%= f.text_area :text, class: "form-control", rows: "10", id: "comment", placeholder: "Type the post text here."  %>
			</p>
			<p>
				<br>
			  <div id = "button-center">
			    <div class="button-center" ><%= f.submit "Create", class: "btn btn-info btn-lg" %></div>
			  </div>
			</p>
		<% end %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="my_field">
  <div class="panel panel-primary">
    <div>
        <h2 class="header-font"><%= @post.name %></h2> <div class = "attributes-f-views" >(<%= pluralize @post.views.size, 'view'%>)</div>
    </div>
      <div class="panel-body">
        <div class="author attributes-f">
        	Author <span class="badge attributes"><%= link_to @post.blog.user.username.capitalize, user_path(@post.blog.user), id: "link-author" %></span>
        </div>

        <div class="date attributes-f">
        	Created <span class="badge attributes"><%= @post.created_at.strftime("%d %b. %Y at %H:%M") %></span>
        </div>
    </div>
    <div class="panel-footer text"><%= @post.text %><br>
      <div class="button-center attributes-f">
        <%= link_to ' To all posts', blog_path(@post.blog_id), class: "btn btn-default" %>
      </div>
      <%= hidden_field_tag :blog_id, @post.blog_id %>
      <% if can? :update && :edit && :destroy, @post%>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary active"  %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default active" %>
      <% end %>
    </div>
  </div>
    <div class="button-center attributes-f">
      <span id = "scroll"><a class = "btn btn-default" href="#comment-form">Leave a comment</a></span>
    </div>
  <div id="comments-count" class="attributes-f-com"> 
    <h5>Comments: <%= @commentable.comments.count %></h5>
  </div>
  <div id="comments-list">
    <%= render @commentable.reload.comments.reverse %>
  </div>
  <div id = "comment-form">
    <%= render 'comments/comment_form'%>
  </div>
</div>